"""Near-match search over registered fingerprints.

Two directions, one machine. An artist searches with a suspected copy and gets
candidates; the log searches on every new registration and alerts the earlier
registrant. The second is the subscription and the reason monitoring closes the
back-catalogue gap that first-to-register leaves open.

**This never returns a verdict.** It returns ranked candidates with their raw
distances, and the banding below is advice about how much attention each
deserves. The costs are wildly asymmetric: a missed match is an annoyance the
artist can search for again, while a false positive is an accusation handed to
someone who did nothing. So it is tuned for precision, there is no field that
could be rendered as "match found", and the strongest band is named
STRONG_CANDIDATE rather than anything that sounds concluded.

Quality overrides distance. A low-detail image — flat colour, line art — has a
fingerprint that collides by coincidence far more often than a photograph's, so
a close distance on such an image means much less. A candidate whose quality is
below the floor is capped at WEAK no matter how close the bits are.

**The thresholds here are provisional and must not be trusted until an eval
harness has run.** They are a starting point chosen to be conservative, not a
measured operating point. Picking real numbers needs a labelled set: positives
generated by recompression, resizing, cropping, rotation, watermarking and
screenshotting, and negatives including the hard ones — the same artist's other
work, the same subject matter, stock photography. Until precision and recall
are measured per threshold per kind, any accuracy claim built on this is
unfounded.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path
from typing import Iterable, Mapping, Sequence

from certifiles.fingerprint import (
    LOW_QUALITY_CEILING,
    Fingerprint,
    FingerprintError,
    FingerprintKind,
    normalised_distance,
    validate_quality,
)

# Provisional. See the module docstring: these are conservative guesses, not
# measurements, and the eval harness is what turns them into numbers worth
# defending. Expressed as fractions of hash width so kinds stay comparable.
TIGHT = 0.12
LOOSE = 0.25

# Scanning every stored fingerprint is linear and correct. Multi-index hashing
# — splitting each hash into bands, matching bands exactly, unioning the
# candidates — is the standard replacement and needs no vector database. Swap
# when measurement says to, not before.
LINEAR_SCAN_ADVISORY_LIMIT = 100_000


class NearMatchError(RuntimeError):
    """The index refused an operation."""


class Band(StrEnum):
    """How much attention a candidate deserves. Never a conclusion."""

    STRONG_CANDIDATE = "strong_candidate"
    POSSIBLE = "possible"
    WEAK = "weak"


@dataclass(frozen=True, slots=True)
class Candidate:
    position: int
    band: Band
    quality: int
    distances: Mapping[FingerprintKind, int]
    quality_capped: bool = False

    @property
    def closest(self) -> float:
        """Smallest normalised distance across the kinds compared."""
        from certifiles.fingerprint import BIT_LENGTHS

        return min(
            normalised_distance(d, BIT_LENGTHS[k]) for k, d in self.distances.items()
        )


SCHEMA = """
CREATE TABLE IF NOT EXISTS fingerprints (
    position INTEGER NOT NULL,
    kind     TEXT NOT NULL,
    value    TEXT NOT NULL,
    quality  INTEGER NOT NULL,
    PRIMARY KEY (position, kind)
);

CREATE INDEX IF NOT EXISTS fingerprints_by_kind ON fingerprints (kind);
"""


class NearMatchIndex:
    """Fingerprints by position, and the search over them.

    Rebuildable from the published log at any time, so it is deliberately not
    append-only: unlike the log, nothing here is evidence, and an index that
    cannot be rebuilt after a bad deploy would be worse than one that can.
    """

    def __init__(self, path: str | Path = ":memory:") -> None:
        self._connection = sqlite3.connect(str(path), isolation_level=None)
        self._connection.executescript(SCHEMA)

    def close(self) -> None:
        self._connection.close()

    def __enter__(self) -> "NearMatchIndex":
        return self

    def __exit__(self, *_exc) -> None:
        self.close()

    def add(
        self, position: int, fingerprints: Iterable[Fingerprint], quality: int
    ) -> None:
        if position < 0:
            raise NearMatchError("position must not be negative")
        validate_quality(quality)
        rows = [(position, str(f.kind), f.value, quality) for f in fingerprints]
        if not rows:
            raise NearMatchError(
                f"position {position} has no fingerprints; a work that cannot be"
                " searched should be recorded as such, not indexed silently"
            )
        self._connection.executemany(
            "INSERT OR REPLACE INTO fingerprints (position, kind, value, quality)"
            " VALUES (?, ?, ?, ?)",
            rows,
        )

    def size(self) -> int:
        return self._connection.execute(
            "SELECT COUNT(DISTINCT position) FROM fingerprints"
        ).fetchone()[0]

    def search(
        self,
        query: Sequence[Fingerprint],
        query_quality: int,
        exclude: Iterable[int] = (),
        limit: int = 25,
        before_position: int | None = None,
    ) -> list[Candidate]:
        """Candidates resembling the query, most attention-worthy first.

        `exclude` keeps an artist's own earlier registrations out of their own
        alerts, which would otherwise be the overwhelming majority of hits.

        `before_position` restricts the search in SQL rather than after it.
        Filtering a truncated result set would let anyone bury an artist's
        alert simply by registering enough later near-matches — the same
        attacker-controlled channel described under AlertPolicy, turned into
        suppression instead of noise.
        """
        if not query:
            raise NearMatchError("a search needs at least one fingerprint")
        validate_quality(query_quality)
        if limit <= 0:
            raise NearMatchError("limit must be positive")
        kinds = [f.kind for f in query]
        if len(set(kinds)) != len(kinds):
            raise NearMatchError(
                "a search has two fingerprints of one algorithm; silently using"
                " the last would miss matches on the first"
            )

        excluded = set(exclude)
        by_kind = {f.kind: f for f in query}
        stored: dict[int, dict[FingerprintKind, Fingerprint]] = {}
        qualities: dict[int, int] = {}

        sql = (
            "SELECT position, kind, value, quality FROM fingerprints WHERE kind IN"
            f" ({','.join('?' * len(by_kind))})"
        )
        parameters: list = [str(k) for k in by_kind]
        if before_position is not None:
            sql += " AND position < ?"
            parameters.append(before_position)

        self.unreadable_rows = 0
        for position, kind, value, quality in self._connection.execute(sql, parameters):
            if position in excluded:
                continue
            try:
                stored.setdefault(position, {})[FingerprintKind(kind)] = Fingerprint(
                    FingerprintKind(kind), value
                )
            except (FingerprintError, ValueError):
                # One drifted row from a partial rebuild must not take down
                # every search. Nothing here is evidence and the index is
                # rebuildable, so skipping and counting beats failing closed.
                self.unreadable_rows += 1
                continue
            # The lowest quality recorded for a position governs. Last-row-wins
            # would make the safety cap depend on SQLite row order, so the same
            # index content could give opposite verdicts.
            qualities[position] = min(qualities.get(position, quality), quality)

        candidates = []
        for position, prints in stored.items():
            distances = {
                kind: by_kind[kind].distance_to(print_)
                for kind, print_ in prints.items()
                if kind in by_kind
            }
            if not distances:
                continue
            # The lower of the two qualities governs: comparing a detailed work
            # against a flat one is only as reliable as the flat one.
            quality = min(qualities[position], query_quality)
            band, capped = classify(distances, quality)
            if band is None:
                continue
            candidates.append(
                Candidate(
                    position=position,
                    band=band,
                    quality=quality,
                    distances=distances,
                    quality_capped=capped,
                )
            )

        order = {Band.STRONG_CANDIDATE: 0, Band.POSSIBLE: 1, Band.WEAK: 2}
        candidates.sort(key=lambda c: (order[c.band], c.closest, c.position))
        return candidates[:limit]


def classify(
    distances: Mapping[FingerprintKind, int],
    quality: int,
    tight: float = TIGHT,
    loose: float = LOOSE,
) -> tuple[Band | None, bool]:
    """Band a set of distances, or None when nothing is close enough to show.

    Agreement across independent algorithms is what separates a strong
    candidate from a coincidence: one hash being close is ordinary, three
    agreeing is not. Returns whether the band was capped by quality so the
    interface can explain a downgrade rather than presenting an unexplained
    rating.
    """
    from certifiles.fingerprint import BIT_LENGTHS

    if not distances:
        return None, False
    validate_quality(quality)

    normalised = {
        kind: normalised_distance(distance, BIT_LENGTHS[kind])
        for kind, distance in distances.items()
    }
    if not 0 <= tight <= loose <= 1:
        raise NearMatchError("thresholds must satisfy 0 <= tight <= loose <= 1")
    within_tight = sum(1 for value in normalised.values() if value <= tight)
    within_loose = sum(1 for value in normalised.values() if value <= loose)

    if within_tight >= 2:
        band = Band.STRONG_CANDIDATE
    elif within_tight >= 1 or within_loose >= 2:
        band = Band.POSSIBLE
    elif within_loose >= 1:
        band = Band.WEAK
    else:
        return None, False

    if quality < LOW_QUALITY_CEILING and band is not Band.WEAK:
        return Band.WEAK, True
    return band, False


@dataclass
class AlertPolicy:
    """Limits on the alert channel.

    Anyone can cause alerts to a chosen artist by registering near-matches to
    their work, so this is an attacker-controlled notification channel aimed at
    exactly the people the product exists to protect. Digesting and capping is
    not a nicety.
    """

    max_alerts_per_recipient_per_day: int = 20
    minimum_band: Band = Band.POSSIBLE
    digest: bool = True

    def admits(self, candidate: Candidate, already_sent_today: int) -> bool:
        order = {Band.STRONG_CANDIDATE: 0, Band.POSSIBLE: 1, Band.WEAK: 2}
        if order[candidate.band] > order[self.minimum_band]:
            return False
        return already_sent_today < self.max_alerts_per_recipient_per_day


def monitor(
    index: NearMatchIndex,
    new_fingerprints: Sequence[Fingerprint],
    new_quality: int,
    new_position: int,
    limit: int = 25,
) -> list[Candidate]:
    """Search triggered by a new registration, for alerting earlier registrants.

    The same search inverted. Only earlier positions can be alerted, because a
    later registration cannot be the thing that was copied from.
    """
    return index.search(
        new_fingerprints,
        new_quality,
        exclude={new_position},
        limit=limit,
        before_position=new_position,
    )
