// Cross-validate the browser verifier against vectors generated by the Python
// implementation. Two verifiers that disagree about what was signed are
// indistinguishable from a forgery, so this is the contract between them.
import { readFileSync } from "node:fs";
import {
  parseCheckpoint, verifyInclusion, keyHash, unhex, hex, fromBase64,
} from "../verifier.js";

const v = JSON.parse(readFileSync(new URL("./vectors.json", import.meta.url)));
let pass = 0, fail = 0;
const fails = [];
const check = (name, ok) => { ok ? pass++ : (fail++, fails.push(name)); };

for (const [i, c] of v.inclusion.entries()) {
  const got = await verifyInclusion(
    unhex(c.leaf), c.index, c.tree_size, c.proof.map(unhex), unhex(c.root),
  );
  check(`inclusion[${i}] size=${c.tree_size} index=${c.index} expect=${c.expect}`,
        got === c.expect);
}

const cp = parseCheckpoint(fromBase64(v.checkpoint.bytes));
check("checkpoint origin", cp.origin === v.checkpoint.origin);
check("checkpoint size", cp.size === BigInt(v.checkpoint.size));
check("checkpoint root", hex(cp.rootHash) === v.checkpoint.root);
check("checkpoint extensions",
      JSON.stringify(cp.extensions) === JSON.stringify(v.checkpoint.extensions));
check("signature names",
      JSON.stringify(cp.signatures.map(s => s.keyName)) ===
      JSON.stringify(v.checkpoint.signature_names));
check("signed body bytes match python",
      hex(cp.body) === hex(fromBase64(v.checkpoint.body)));
for (const s of cp.signatures) {
  check(`key hash ${s.keyName}`,
        hex(s.keyHash) === v.checkpoint.key_hashes[s.keyName]);
}
check("key hash derivation matches python",
      hex(await keyHash("witness-a", new Uint8Array(32).fill(0xBB))) ===
      v.checkpoint.key_hashes["witness-a"]);

for (const [name, b64] of Object.entries(v.malformed_checkpoints)) {
  let rejected = false;
  try { parseCheckpoint(fromBase64(b64)); } catch { rejected = true; }
  check(`malformed rejected: ${name}`, rejected);
}

console.log(`  ${pass} agreed, ${fail} disagreed`);
if (fail) { fails.slice(0, 10).forEach(f => console.log(`    DISAGREE: ${f}`)); process.exit(1); }

// ---- near-match banding --------------------------------------------------
import { classify, TIGHT, LOOSE, LOW_QUALITY_CEILING } from "../nearmatch.js";
const nm = JSON.parse(readFileSync(new URL("./nearmatch-vectors.json", import.meta.url)));
check("tight threshold matches python", TIGHT === nm.tight);
check("loose threshold matches python", LOOSE === nm.loose);
check("quality ceiling matches python", LOW_QUALITY_CEILING === nm.low_quality_ceiling);
let nmPass = 0;
for (const [i, c] of nm.cases.entries()) {
  const got = classify(c.distances, c.quality);
  const ok = (got.band ?? null) === c.band && got.qualityCapped === c.capped;
  check(`band[${i}] ${JSON.stringify(c.distances)} q=${c.quality}`, ok);
  if (ok) nmPass++;
}
console.log(`  ${nmPass}/${nm.cases.length} banding decisions agreed`);
if (fail) process.exit(1);
